"""
The candidate profile visualization, Stage 4.

The assignment asks that a validated candidate profile be rendered as a short
HTML or Markdown document. This module does that, and it is the last thing the
pipeline produces:

    validator.validate(source)  ->  model  ->  to_html(model)
                                           ->  to_markdown(model)


IT RENDERS THE MODEL, NOT THE SOURCE

The argument is the object textX built, never the profile text. Rendering the
text would mean parsing it a second time, with a second, informal grammar
written in Python, and the two would drift. Taking the model also means that
nothing reaches this module without having been validated first, so the
renderer has no error case to handle: every field it reads is a field the
grammar guaranteed.


IT SHOWS THE CANONICAL SYMBOLS AS THEY ARE

A qualification is displayed as GIT and a classification as
FULL_STACK_DEVELOPER, rather than as "Git" and "Full Stack Developer". Those
prettier names live in src/classification/profiles.py, and importing them here
would make Stage 4 depend on Stage 3 for presentation, which
docs/architecture.md section 7 keeps the stages free of.

There is a better reason than the dependency. The canonical symbol is what the
system actually concluded: it is the output of the transducer of section 3 and
the input of the automata of section 4. Showing it keeps the document
traceable back to the formal models, which is the point of the application,
and spares the reader the question of whether "Full Stack Developer" is a
title someone wrote in the résumé or a result the system computed.


WHAT IT SAYS WHEN A VALUE IS EMPTY

The generator writes an empty string where the résumé stated nothing, so the
renderer prints "not stated" rather than leaving a blank. A candidate profile
that quietly shows nothing where a job title should be reads as though the
information were missing from the system, not from the résumé.
"""

from html import escape


NOT_STATED = "not stated"

# The style is deliberately small: a readable serif column with a little
# spacing. The assignment asks for a short visualization that opens in a
# browser, and a document that depends on a stylesheet it cannot find is not
# that, so everything is embedded in the file.

STYLE = """\
    body {
        font-family: Georgia, 'Times New Roman', serif;
        line-height: 1.5;
        margin: 2rem auto;
        max-width: 42rem;
        padding: 0 1rem;
        color: #222;
    }
    h1 { margin-bottom: 0.2rem; }
    h2 {
        font-size: 1.05rem;
        text-transform: uppercase;
        letter-spacing: 0.08em;
        border-bottom: 1px solid #ccc;
        padding-bottom: 0.2rem;
        margin-top: 2rem;
    }
    .contact { color: #555; margin-top: 0; }
    .symbol {
        font-family: 'Courier New', monospace;
        font-size: 0.9rem;
        background: #f2f2f2;
        border: 1px solid #ddd;
        padding: 0.1rem 0.4rem;
        display: inline-block;
        margin: 0.1rem 0.2rem 0.1rem 0;
    }
    .record { margin-bottom: 0.8rem; }
    .empty { color: #777; font-style: italic; }
    footer {
        margin-top: 2.5rem;
        border-top: 1px solid #ccc;
        padding-top: 0.6rem;
        font-size: 0.85rem;
        color: #666;
    }
"""

# The application evaluates qualification patterns, it does not rank or decide.
# The assignment states this and the document repeats it, because a page that
# lists a person and a verdict will be read as a recommendation unless it says
# otherwise.

DISCLAIMER = (
    "Generated by ResumeLens from the candidate profile language. "
    "ResumeLens reports whether the qualifications stated in a résumé satisfy "
    "a formally defined pattern. It does not rank candidates and does not make "
    "hiring decisions."
)


def name_of(model):
    """The candidate's name, or the placeholder when the résumé stated none."""

    return model.personal.name or NOT_STATED


def to_html(model):
    """
    Render a validated profile as a complete HTML document.

    The result is self contained: no stylesheet, no script, no image. Saving it
    to a file and opening it in a browser is all it needs, which is what the
    assignment asks for.
    """

    parts = [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="utf-8">',
        f"<title>{escape(name_of(model))} — ResumeLens</title>",
        f"<style>\n{STYLE}</style>",
        "</head>",
        "<body>",
        f"<h1>{escape(name_of(model))}</h1>",
        f'<p class="contact">{_contact_line(model)}</p>',
        _html_section("Profile classification", _html_classifications(model)),
        _html_section("Education", _html_education(model)),
        _html_section("Professional experience", _html_experience(model)),
        _html_section("Normalized qualifications", _html_skills(model)),
        f"<footer>{escape(DISCLAIMER)}</footer>",
        "</body>",
        "</html>",
    ]

    return "\n".join(parts) + "\n"


def to_markdown(model):
    """
    Render a validated profile as Markdown, for a terminal or a repository.

    The same content as to_html, in the format the assignment offers as the
    alternative.
    """

    lines = [
        f"# {name_of(model)}",
        "",
        _markdown_contact(model),
        "",
        "## Profile classification",
        "",
    ]

    if model.classifications:
        lines += [f"- `{entry.profile}`" for entry in model.classifications]
    else:
        lines.append("_No profile pattern was satisfied._")

    lines += ["", "## Education", ""]

    if model.educations:
        for record in model.educations:
            lines.append(f"- **{record.degree or NOT_STATED}**, "
                         f"{record.field or NOT_STATED}"
                         + (f" ({record.institution})"
                            if record.institution else ""))
    else:
        lines.append("_No academic qualification was stated._")

    lines += ["", "## Professional experience", ""]

    if model.experiences:
        for record in model.experiences:
            lines.append(f"- {record.position or NOT_STATED}, "
                         f"{record.years} year(s)")
    else:
        lines.append("_No professional experience was stated._")

    lines += ["", "## Normalized qualifications", ""]

    if model.skills.skills:
        lines.append(" ".join(
            f"`{skill.symbol}`" for skill in model.skills.skills
        ))
    else:
        lines.append("_No qualification of the controlled vocabulary was "
                     "recognized._")

    lines += ["", "---", "", DISCLAIMER, ""]

    return "\n".join(lines)


def _contact_line(model):
    pieces = [escape(model.personal.email)]

    if model.personal.phone:
        pieces.append(escape(model.personal.phone))

    return " · ".join(pieces)


def _markdown_contact(model):
    pieces = [model.personal.email]

    if model.personal.phone:
        pieces.append(model.personal.phone)

    return " · ".join(pieces)


def _html_section(heading, body):
    return f"<h2>{escape(heading)}</h2>\n{body}"


def _empty(message):
    return f'<p class="empty">{escape(message)}</p>'


def _html_classifications(model):
    if not model.classifications:
        return _empty("No profile pattern was satisfied.")

    symbols = "".join(
        f'<span class="symbol">{escape(entry.profile)}</span>'
        for entry in model.classifications
    )

    return f"<p>{symbols}</p>"


def _html_education(model):
    if not model.educations:
        return _empty("No academic qualification was stated.")

    records = []

    for record in model.educations:
        line = (f"<strong>{escape(record.degree or NOT_STATED)}</strong>, "
                f"{escape(record.field or NOT_STATED)}")

        if record.institution:
            line += f"<br>{escape(record.institution)}"

        records.append(f'<p class="record">{line}</p>')

    return "\n".join(records)


def _html_experience(model):
    if not model.experiences:
        return _empty("No professional experience was stated.")

    return "\n".join(
        f'<p class="record"><strong>'
        f"{escape(record.position or NOT_STATED)}</strong>, "
        f"{record.years} year(s)</p>"
        for record in model.experiences
    )


def _html_skills(model):
    if not model.skills.skills:
        return _empty(
            "No qualification of the controlled vocabulary was recognized."
        )

    symbols = "".join(
        f'<span class="symbol">{escape(skill.symbol)}</span>'
        for skill in model.skills.skills
    )

    return f"<p>{symbols}</p>"